import { dotnet } from '../dist/_framework/dotnet.js';
const runtime = await dotnet.withDiagnosticTracing(false).create();
const exports = await runtime.getAssemblyExports(runtime.getConfig().mainAssemblyName);
const bridge = exports.RoslynBrowser.CompilerBridge;
const version = JSON.parse(bridge.Version());
console.log('WASM_VERSION', JSON.stringify(version));
if(version.referenceCount < 150) throw new Error('Missing reference assemblies');
const result = JSON.parse(bridge.Compile(JSON.stringify({source:'using System; using System.Linq; using System.Threading.Tasks; public record Item(int Value); class Program { public static async Task<int> Main(string[] args) { await Task.Yield(); Console.WriteLine("wasm="+new[]{new Item(4),new Item(6)}.Select(x=>x.Value).Sum()); return 7; } }', includeInspection:true})));
if(!result.success) throw new Error(JSON.stringify(result));
console.log('WASM_COMPILE',JSON.stringify({success:result.success,peBytes:result.peBase64.length*0.75,diagnostics:result.diagnostics,types:result.inspection.types.length}));
const run = JSON.parse(await bridge.Run(result.assemblyId, '[]'));
console.log('WASM_RUN',JSON.stringify(run));
if(!run.success || run.exitCode!==7 || !run.stdout.includes('wasm=10')) throw new Error('WASM execution failed');
const lib=JSON.parse(bridge.Compile(JSON.stringify({source:'namespace DemoLib; public static class Calc { public static long Twice(long x) => x*2; }',outputKind:'library',assemblyName:'DemoLib'})));
if(!lib.success) throw new Error(JSON.stringify(lib));
console.log('ADD_REFERENCE',bridge.AddReference('DemoLib.dll',lib.peBase64));
console.log('ADD_ASSEMBLY',bridge.AddAssembly('DemoLib.dll',lib.peBase64));
const consumer=JSON.parse(bridge.Compile(JSON.stringify({source:'System.Console.WriteLine(DemoLib.Calc.Twice(21));'})));
if(!consumer.success) throw new Error(JSON.stringify(consumer));
const dependencyRun=JSON.parse(await bridge.Run(consumer.assemblyId,'[]'));
console.log('WASM_DEPENDENCY',JSON.stringify(dependencyRun));
if(!dependencyRun.success || dependencyRun.stdout.trim()!=='42') throw new Error('WASM dependency load failed');
const invoke=JSON.parse(await bridge.Invoke(lib.assemblyId,'DemoLib.Calc','Twice','[19]'));
console.log('WASM_INVOKE',JSON.stringify(invoke));
if(!invoke.success || invoke.result?.$int64!=='38') throw new Error('WASM Invoke failed');
console.log('ALL WASM SMOKE ASSERTIONS PASSED');
process.exit(0);
