import assert from 'node:assert/strict';
import test from 'node:test';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {compileAssembly} from '../src/il/compiler.mjs';
import {compileWasm,loadWasm} from '../src/wasm/index.js';
import {createRuntime,i4} from '../src/il/runtime.mjs';
import {isCadStringsBuiltin,invokeCadStringsBuiltin,compareInvariantCadStrings,invariantCadStringKey} from '../src/il/cad-strings.mjs';
const source=readFileSync(new URL('./cad-strings-fixture.cs',import.meta.url),'utf8'),model=JSON.parse(readFileSync(new URL('./cad-strings-fixture.json',import.meta.url))),baseline=JSON.parse(readFileSync(new URL('./cad-strings-baseline.json',import.meta.url)));
test('string fixture and pinned managed oracle source agree',()=>assert.equal(baseline.sourceSha256,createHash('sha256').update(source).digest('hex')));
test('native CLR and managed Wasm oracle hashes agree for every portable string scenario',()=>{const native=JSON.parse(readFileSync(new URL('./cad-strings-native-baseline.json',import.meta.url)));assert.equal(native.sourceSha256,baseline.sourceSha256);for(const item of native.cases){const expected=baseline.cases.find(value=>value.method===item.method);assert.equal(item.results,expected.result.length);assert.equal(item.sha256,createHash('sha256').update(JSON.stringify(expected.result)).digest('hex'),item.method);}});

for(const optimize of [false,'blocks',true])test(`string/split/comparer/builder managed oracle, JavaScript optimize=${optimize}`,()=>{const program=compileAssembly(model,{strict:true,optimize});for(const item of baseline.cases)assert.deepEqual(program.invoke(`CadStringsFixture::${item.method}`),item.result,item.method);});
for(const optimize of [false,true])test(`string/split/comparer/builder managed oracle, native Wasm optimize=${optimize}`,async()=>{const a=compileWasm(model,{optimize,exports:baseline.cases.map(item=>item.method)}),program=await loadWasm(a.bytes);try{for(const item of baseline.cases)assert.deepEqual(program.invoke(`CadStringsFixture::${item.method}`),item.result,item.method);}finally{program.dispose();}});
const ref=(type,name,result,parameters=[],isStatic=false)=>({declaringType:type,name,returnType:result,parameters,isStatic,genericParameterCount:0});
test('string admission checks staticness, result, parameters and generic arity',()=>{const r=ref('System.String','Split','System.String[]',['System.Char','System.StringSplitOptions']);assert.equal(isCadStringsBuiltin(r),true);for(const changed of [{isStatic:true},{returnType:'System.Object'},{parameters:['System.Char','System.Int32']},{genericParameterCount:1},{genericArguments:['System.Char']}])assert.equal(isCadStringsBuiltin({...r,...changed}),false);});
test('invariant collation preserves punctuation weights and explicitly rejects unsupported Unicode',()=>{assert.equal(compareInvariantCadStrings('_a','-a'),-1);assert.equal(compareInvariantCadStrings('A\0b','ab'),0);for(const s of ['é','İ','ß','\u0001','\uD800'])assert.throws(()=>invariantCadStringKey(s),error=>error.runtimeLimitation===true);assert.throws(()=>invariantCadStringKey('a\0',true),error=>error.runtimeLimitation===true);});
test('StringBuilder append and split enforce configured allocation bounds',()=>{const rt=createRuntime(model,{maxArrayLength:8}),self={$type:'System.Text.StringBuilder',fields:{}};invokeCadStringsBuiltin(rt,ref(self.$type,'.ctor','System.Void',['System.Int32']),[i4(0)],self);const append=ref(self.$type,'Append',self.$type,['System.String']);invokeCadStringsBuiltin(rt,append,['12345678'],self);assert.throws(()=>invokeCadStringsBuiltin(rt,append,['x'],self),error=>error.runtimeLimitation===true);assert.equal(invokeCadStringsBuiltin(rt,ref(self.$type,'ToString','System.String'),[],self).value,'12345678');const split=ref('System.String','Split','System.String[]',['System.Char','System.StringSplitOptions']);assert.throws(()=>invokeCadStringsBuiltin(rt,split,[i4(44),i4(0)],',,,,,,,,,'),error=>error.runtimeLimitation===true);});
test('environment identity is explicit, and directory changes use only each runtime virtual filesystem',()=>{const first=createRuntime(model,{environment:{userName:'CAD user'}}),second=createRuntime(model);const get=ref('System.Environment','get_CurrentDirectory','System.String',[],true),set=ref('System.Environment','set_CurrentDirectory','System.Void',['System.String'],true);assert.equal(first.callBuiltin(ref('System.Environment','get_UserName','System.String',[],true),[],null).value,'CAD user');assert.equal(second.callBuiltin(ref('System.Environment','get_UserName','System.String',[],true),[],null).value,'Browser');first.callBuiltin(ref('System.IO.Directory','CreateDirectory','System.IO.DirectoryInfo',['System.String'],true),['/drawings'],null);first.callBuiltin(set,['/drawings'],null);assert.equal(first.callBuiltin(get,[],null).value,'/drawings');assert.equal(second.callBuiltin(get,[],null).value,'/');assert.throws(()=>first.callBuiltin(set,['/missing'],null),error=>error.$type==='System.IO.DirectoryNotFoundException');});
