using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
public sealed class DescendingComparer : Comparer<int> { public override int Compare(int a,int b)=>b.CompareTo(a); }
public sealed class ComparableValue : IComparable<ComparableValue> {
 public int Value; public ComparableValue(int value){Value=value;} public int CompareTo(ComparableValue other)=>Value.CompareTo(other.Value);
 public override bool Equals(object other)=>other is ComparableValue v&&Value==v.Value;
 public override int GetHashCode()=>Value;
}
public static class CollectionsFixture {
 public static string QueueOrder(){var q=new Queue<int>(new[]{1,2,3});q.Enqueue(4);int first=q.Dequeue();q.TryDequeue(out var second);q.TryPeek(out var third);return first+":"+second+":"+third+":"+string.Join(",",q.Select(x=>x.ToString()).ToArray());}
 public static int QueueEmpty(){var q=new Queue<long>();int r=0;if(!q.TryDequeue(out var v)&&v==0)r++;if(!q.TryPeek(out v)&&v==0)r++;try{q.Dequeue();}catch(InvalidOperationException){r+=10;}try{q.Peek();}catch(InvalidOperationException){r+=30;}return r;}
 public static string QueueCopyCapacity(){var q=new Queue<int>(2);q.Enqueue(1);q.Enqueue(2);var c=q.EnsureCapacity(8);q.Dequeue();q.Enqueue(3);var dest=new int[4];q.CopyTo(dest,1);q.TrimExcess();return c+":"+string.Join(",",dest.Select(x=>x.ToString()).ToArray())+":"+q.Contains(3);}
 public static int QueueVersion(){var q=new Queue<int>(new[]{1,2});var e=q.GetEnumerator();q.Enqueue(3);try{e.MoveNext();return 0;}catch(InvalidOperationException){return 42;}}
 public static string StackOrder(){var s=new Stack<int>(new[]{1,2,3});s.Push(4);s.TryPop(out var a);s.TryPeek(out var b);var c=s.Pop();return a+":"+b+":"+c+":"+string.Join(",",s.ToArray().Select(x=>x.ToString()).ToArray());}
 public static int StackEmpty(){var s=new Stack<int>();int r=0;if(!s.TryPop(out var v)&&v==0)r++;if(!s.TryPeek(out v)&&v==0)r++;try{s.Pop();}catch(InvalidOperationException){r+=10;}try{s.Peek();}catch(InvalidOperationException){r+=30;}return r;}
 public static string StackCopyCapacity(){var s=new Stack<int>(new[]{1,2,3});var c=s.EnsureCapacity(9);s.TrimExcess();var a=new int[5];s.CopyTo(a,1);return c+":"+string.Join(",",a.Select(x=>x.ToString()).ToArray())+":"+s.Contains(1);}
 public static int StackVersion(){var s=new Stack<int>(new[]{1,2});var e=s.GetEnumerator();e.MoveNext();s.Pop();try{e.MoveNext();return 0;}catch(InvalidOperationException){return 42;}}
 public static string LinkedNodes(){var l=new LinkedList<int>();var b=l.AddLast(2);l.AddBefore(b,1);l.AddAfter(b,3);l.AddFirst(0);var last=new LinkedListNode<int>(4);l.AddLast(last);b.Value=20;var text=string.Join(",",l.Select(x=>x.ToString()).ToArray());l.RemoveFirst();l.RemoveLast();return text+":"+b.Previous.Value+":"+b.Next.Value+":"+(last.List==null)+":"+l.Count;}
 public static int LinkedOwnership(){var a=new LinkedList<int>();var b=new LinkedList<int>();var node=a.AddFirst(1);int r=0;try{b.AddFirst(node);}catch(InvalidOperationException){r+=1;}try{b.Remove(node);}catch(InvalidOperationException){r+=1;}a.Remove(node);b.AddLast(node);if(node.List==b)r+=10;a.Clear();b.Clear();if(node.List==null&&node.Next==null&&node.Previous==null)r+=30;return r;}
 public static string LinkedFind(){var l=new LinkedList<string>(new[]{"a",null,"a","b"});var first=l.Find("a");var last=l.FindLast("a");var n=l.Find(null);l.Remove("a");var a=new string[5];l.CopyTo(a,1);return (first.List==null)+":"+(last.List==l)+":"+(n.Value==null)+":"+string.Join(",",a);}
 public static int LinkedLiveValue(){var l=new LinkedList<int>(new[]{1,2});var e=l.GetEnumerator();l.First.Value=40;e.MoveNext();int v=e.Current;l.Last.Value=2;e.MoveNext();return v+e.Current;}
 public static int LinkedVersion(){var l=new LinkedList<int>(new[]{1,2});var e=l.GetEnumerator();l.AddFirst(3);try{e.MoveNext();return 0;}catch(InvalidOperationException){return 42;}}
 public static string SortedSetOrder(){var s=new SortedSet<int>(new[]{4,2,3,2,1});bool add=s.Add(3);s.TryGetValue(2,out var found);return string.Join(",",s.Select(x=>x.ToString()).ToArray())+":"+s.Min+":"+s.Max+":"+add+":"+found+":"+string.Join(",",s.Reverse().Select(x=>x.ToString()).ToArray());}
 public static string SortedSetAlgebra(){var s=new SortedSet<int>(new[]{1,2,3});s.UnionWith(new[]{3,4});s.IntersectWith(new[]{2,3,4,5});s.ExceptWith(new[]{3});s.SymmetricExceptWith(new[]{4,5,5});return string.Join(",",s.Select(x=>x.ToString()).ToArray())+":"+s.IsSubsetOf(new[]{2,5,7})+":"+s.IsProperSubsetOf(new[]{2,5,7})+":"+s.IsSupersetOf(new[]{2})+":"+s.IsProperSupersetOf(new[]{2})+":"+s.Overlaps(new[]{5,8})+":"+s.SetEquals(new[]{5,2,2});}
 public static string SortedView(){var s=new SortedSet<int>(new[]{1,2,3,4,5});var v=s.GetViewBetween(2,4);s.Add(0);v.Remove(3);v.Add(3);int errors=0;try{v.Add(7);}catch(ArgumentOutOfRangeException){errors++;}var nested=v.GetViewBetween(3,4);nested.Clear();return v.Count+":"+v.Min+":"+errors+":"+string.Join(",",s.Select(x=>x.ToString()).ToArray());}
 public static string SortedSetComparers(){var a=new SortedSet<int>(new DescendingComparer()){1,4,2};var b=new SortedSet<int>(Comparer<int>.Create((x,y)=>y.CompareTo(x))){3,1,2};var c=new SortedSet<string>(StringComparer.OrdinalIgnoreCase){"Alpha","ALPHA","beta"};return string.Join(",",a.Select(x=>x.ToString()).ToArray())+":"+string.Join(",",b.Select(x=>x.ToString()).ToArray())+":"+c.Count+":"+c.Contains("BETA")+":"+StringComparer.Ordinal.Compare("a","b");}
 public static int SortedComparable(){var s=new SortedSet<ComparableValue>();s.Add(new ComparableValue(2));s.Add(new ComparableValue(1));s.Add(new ComparableValue(2));return s.Count*20+s.Min.Value+s.Max.Value-1;}
 public static string SortedSetCopy(){var s=new SortedSet<int>(new[]{1,2,3,4});var r=s.RemoveWhere(x=>x%2==0);var a=new int[5];s.CopyTo(a,1,2);return r+":"+string.Join(",",a.Select(x=>x.ToString()).ToArray());}
 public static int SortedSetVersion(){var s=new SortedSet<int>{1,2};var e=s.GetEnumerator();s.Add(2);try{e.MoveNext();return 0;}catch(InvalidOperationException){return 42;}}
 public static string SortedDictionaryOrder(){var d=new SortedDictionary<int,string>();d.Add(3,"c");d[1]="a";d.Add(2,"b");d[2]="B";d.TryGetValue(2,out var value);d.TryGetValue(5,out var missing);return string.Join(",",d.Keys.Select(x=>x.ToString()).ToArray())+":"+string.Join(",",d.Values.ToArray())+":"+value+":"+(missing==null)+":"+d.ContainsValue("B")+":"+d.Remove(3)+":"+d.Count;}
 public static string SortedDictionaryCopy(){var original=new Dictionary<int,string>{{2,"b"},{1,"a"}};var d=new SortedDictionary<int,string>(original,new DescendingComparer());var keys=d.Keys;var values=d.Values;d.Add(3,"c");return keys.Count+":"+values.Count+":"+string.Join(",",d.Select(x=>x.Key+"="+x.Value).ToArray());}
 public static int SortedDictionaryErrors(){var d=new SortedDictionary<string,int>(StringComparer.Ordinal);d.Add("a",1);int result=0;try{d.Add("a",2);}catch(ArgumentException){result+=1;}try{d.Add(null,2);}catch(ArgumentNullException){result+=1;}try{var x=d["missing"];}catch(KeyNotFoundException){result+=10;}var e=d.GetEnumerator();d["a"]=3;try{e.MoveNext();}catch(InvalidOperationException){result+=30;}return result;}
 public static string StringOrdinal(){var s=new SortedSet<string>(StringComparer.Ordinal){"z","Z","é","e","😀"};return string.Join(",",s.ToArray());}
 public static int EmptyCopyErrors(){int r=0;var q=new Queue<int>(new[]{1});try{q.CopyTo(new int[1],-1);}catch(ArgumentOutOfRangeException){r++;}try{q.CopyTo(new int[0],0);}catch(ArgumentException){r++;}var l=new LinkedList<int>();try{l.RemoveLast();}catch(InvalidOperationException){r+=10;}try{new Stack<int>(-1);}catch(ArgumentOutOfRangeException){r+=30;}return r;}
 public static int ValueEquality(){var q=new Queue<ComparableValue>();q.Enqueue(new ComparableValue(42));var l=new LinkedList<ComparableValue>();l.AddLast(new ComparableValue(42));return q.Contains(new ComparableValue(42))&&l.Contains(new ComparableValue(42))?42:0;}
 public static int EnumeratorCopy(){var q=new Queue<int>(new[]{20,22});var a=q.GetEnumerator();var b=a;a.MoveNext();a.MoveNext();b.MoveNext();return a.Current+b.Current;}
 public static int InterfaceIdentity(){object q=new Queue<string>();object s=new Stack<int>();object l=new LinkedList<int>();object set=new SortedSet<int>();object d=new SortedDictionary<int,string>();int n=0;if(q is IEnumerable<object> && q is IReadOnlyCollection<string> && !(q is ICollection<string>))n++;if(s is IEnumerable<int> && !(s is IEnumerable<object>))n++;if(l is ICollection<int> && l is IReadOnlyCollection<int>)n+=10;if(set is ISet<int> && set is IReadOnlySet<int>)n+=10;if(d is IReadOnlyDictionary<int,string> && d is IDictionary && !(d is IDictionary<string,int>))n+=20;return n;}
 public static string InterfaceCount(){IReadOnlyCollection<int> q=new Queue<int>(new[]{1,2,3});ICollection<int> l=new LinkedList<int>(new[]{1,2});var d=new SortedDictionary<int,string>{{1,"a"}};ICollection<string> values=d.Values;return q.Count+":"+l.Count+":"+l.IsReadOnly+":"+values.IsReadOnly;}
 public static int KeysEnumerator(){var d=new SortedDictionary<int,int>{{20,1},{22,2}};int total=0;foreach(var key in d.Keys)total+=key;var e=d.Values.GetEnumerator();e.MoveNext();total+=e.Current;return total-1;}
 public static int EnumeratorInterfaces(){object q=new Queue<string>(new[]{"a"}).GetEnumerator();object d=new SortedDictionary<int,int>{{1,2}}.GetEnumerator();return q is IEnumerator<string> && q is IEnumerator<object> && q is IDisposable && d is IEnumerator<KeyValuePair<int,int>>?42:0;}
 public static long ExactLongValues(){var q=new Queue<long>();q.Enqueue(9007199254740993L);var s=new SortedSet<long>{9007199254740994L,9007199254740993L};var l=new LinkedList<long>();l.AddFirst(q.Dequeue());return s.Max+l.First.Value;}
 public static int ResetEnumerator(){var q=new Queue<int>(new[]{20,22});IEnumerator e=q.GetEnumerator();e.MoveNext();e.MoveNext();int a=(int)e.Current;e.Reset();e.MoveNext();return a+(int)e.Current;}
 public static string EmptyEnumerator(){var s=new SortedSet<int>();var l=new LinkedList<int>();var d=new SortedDictionary<int,string>();return s.GetEnumerator().Current+":"+l.GetEnumerator().Current+":"+d.GetEnumerator().Current.Key+":"+(d.GetEnumerator().Current.Value==null);}
}
