using System;
using System.Reflection;
using System.Reflection.Emit;
public interface IEmittedValue { int Value(); }
public class EmitBase { public virtual int Number() => 1; }
public static class EmitTypeFixture
{
 static ModuleBuilder Module(string name) => AssemblyBuilder.DefineDynamicAssembly(new AssemblyName(name), AssemblyBuilderAccess.Run).DefineDynamicModule(name);
 static TypeBuilder Type(string name) => Module(name + "Assembly").DefineType(name, TypeAttributes.Public);
 static void Constant(ILGenerator il, int value) { il.Emit(OpCodes.Ldc_I4, value); il.Emit(OpCodes.Ret); }
 public static int ObjectConstructorReflection() => typeof(object).GetConstructor(System.Type.EmptyTypes)!.Invoke(null)!.GetType() == typeof(object) ? 42 : 0;
 public static int StaticMethod() { var t=Type("MathType");var m=t.DefineMethod("Answer",MethodAttributes.Public|MethodAttributes.Static,typeof(int),new[]{typeof(int)});var il=m.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldc_I4,2);il.Emit(OpCodes.Mul);il.Emit(OpCodes.Ret);var created=t.CreateType()!;return (int)created.GetMethod("Answer")!.Invoke(null,new object[]{21})!; }
 public static int ConstructorField() { var t=Type("CounterType");var f=t.DefineField("Value",typeof(int),FieldAttributes.Public);var ctor=t.DefineConstructor(MethodAttributes.Public,CallingConventions.Standard,new[]{typeof(int)});var il=ctor.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Call,typeof(object).GetConstructor(System.Type.EmptyTypes)!);il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldarg_1);il.Emit(OpCodes.Stfld,f);il.Emit(OpCodes.Ret);var ct=t.CreateType()!;var a=Activator.CreateInstance(ct,new object[]{20})!;var b=Activator.CreateInstance(ct,new object[]{22})!;return (int)ct.GetField("Value")!.GetValue(a)!+(int)ct.GetField("Value")!.GetValue(b)!; }
 public static int Property() { var t=Type("PropertyType");var f=t.DefineField("_value",typeof(int),FieldAttributes.Private);var p=t.DefineProperty("Value",PropertyAttributes.None,typeof(int),null);var get=t.DefineMethod("get_Value",MethodAttributes.Public|MethodAttributes.SpecialName,typeof(int),System.Type.EmptyTypes);var il=get.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldfld,f);il.Emit(OpCodes.Ret);var set=t.DefineMethod("set_Value",MethodAttributes.Public|MethodAttributes.SpecialName,typeof(void),new[]{typeof(int)});il=set.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldarg_1);il.Emit(OpCodes.Stfld,f);il.Emit(OpCodes.Ret);p.SetGetMethod(get);p.SetSetMethod(set);var ct=t.CreateTypeInfo()!.AsType();var obj=Activator.CreateInstance(ct)!;var prop=ct.GetProperty("Value")!;prop.SetValue(obj,42);return (int)prop.GetValue(obj)!; }
 public static int StaticInitializer() { var t=Type("StaticType");var f=t.DefineField("Counter",typeof(int),FieldAttributes.Public|FieldAttributes.Static);var init=t.DefineTypeInitializer().GetILGenerator();init.Emit(OpCodes.Ldc_I4,40);init.Emit(OpCodes.Stsfld,f);init.Emit(OpCodes.Ret);var m=t.DefineMethod("Next",MethodAttributes.Public|MethodAttributes.Static,typeof(int),System.Type.EmptyTypes);var il=m.GetILGenerator();il.Emit(OpCodes.Ldsfld,f);il.Emit(OpCodes.Ldc_I4_1);il.Emit(OpCodes.Add);il.Emit(OpCodes.Dup);il.Emit(OpCodes.Stsfld,f);il.Emit(OpCodes.Ret);var ct=t.CreateType()!;ct.GetMethod("Next")!.Invoke(null,null);return (int)ct.GetMethod("Next")!.Invoke(null,null)!; }
 public static int MemberReferences() { var t=Type("CallsType");var first=t.DefineMethod("First",MethodAttributes.Public|MethodAttributes.Static,typeof(int),System.Type.EmptyTypes);Constant(first.GetILGenerator(),21);var second=t.DefineMethod("Second",MethodAttributes.Public|MethodAttributes.Static,typeof(int),System.Type.EmptyTypes);var il=second.GetILGenerator();il.Emit(OpCodes.Call,first);il.Emit(OpCodes.Ldc_I4_2);il.Emit(OpCodes.Mul);il.Emit(OpCodes.Ret);var ct=t.CreateType()!;return (int)ct.GetMethod("Second")!.Invoke(null,null)!; }
 public static int Delegate() { var t=Type("DelegateType");var m=t.DefineMethod("Double",MethodAttributes.Public|MethodAttributes.Static,typeof(int),new[]{typeof(int)});var il=m.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ldc_I4_2);il.Emit(OpCodes.Mul);il.Emit(OpCodes.Ret);var ct=t.CreateType()!;return ((Func<int,int>)ct.GetMethod("Double")!.CreateDelegate(typeof(Func<int,int>)))(21); }
 public static int ExplicitInterface() { var t=Type("InterfaceType");t.AddInterfaceImplementation(typeof(IEmittedValue));var m=t.DefineMethod("HiddenValue",MethodAttributes.Private|MethodAttributes.Virtual|MethodAttributes.Final|MethodAttributes.NewSlot,typeof(int),System.Type.EmptyTypes);Constant(m.GetILGenerator(),42);t.DefineMethodOverride(m,typeof(IEmittedValue).GetMethod("Value")!);return ((IEmittedValue)Activator.CreateInstance(t.CreateType()!)!).Value(); }
 public static int Inheritance() { var t=Type("DerivedType");t.SetParent(typeof(EmitBase));var m=t.DefineMethod("Number",MethodAttributes.Public|MethodAttributes.Virtual,typeof(int),System.Type.EmptyTypes);Constant(m.GetILGenerator(),42);return ((EmitBase)Activator.CreateInstance(t.CreateType()!)!).Number(); }
 public static string Metadata() { var module=Module("MetadataAssembly");var t=module.DefineType("Demo.MetadataType",TypeAttributes.Public|TypeAttributes.Sealed);t.DefineDefaultConstructor(MethodAttributes.Public);var m=t.DefineMethod("Named",MethodAttributes.Public|MethodAttributes.Static,typeof(int),new[]{typeof(int)});m.DefineParameter(1,ParameterAttributes.None,"input");var il=m.GetILGenerator();il.Emit(OpCodes.Ldarg_0);il.Emit(OpCodes.Ret);var ct=t.CreateType()!;return ct.FullName+":"+ct.Namespace+":"+ct.Assembly.GetName().Name+":"+ct.GetMethod("Named")!.GetParameters()[0].Name+":"+ct.IsSealed+":"+t.IsCreated(); }
 public static int MultipleTypes() { var module=Module("MultiAssembly");var a=module.DefineType("FirstType",TypeAttributes.Public);a.DefineDefaultConstructor(MethodAttributes.Public);var at=a.CreateType()!;var field=a.GetField("unused");var b=module.DefineType("SecondType",TypeAttributes.Public);b.DefineDefaultConstructor(MethodAttributes.Public);var bt=b.CreateType()!;return at.Assembly.GetTypes().Length+bt.GetConstructors().Length; }
 public static int Literal() { var t=Type("LiteralType");var f=t.DefineField("Answer",typeof(long),FieldAttributes.Public|FieldAttributes.Static|FieldAttributes.Literal);f.SetConstant(9007199254740993L);return (long)t.CreateType()!.GetField("Answer")!.GetRawConstantValue()! == 9007199254740993L ? 42 : 0; }
 public static int MutationRejected() {var t=Type("FrozenType");var m=t.DefineMethod("Get",MethodAttributes.Public|MethodAttributes.Static,typeof(int),System.Type.EmptyTypes);Constant(m.GetILGenerator(),42);t.CreateType();try { t.DefineField("Late",typeof(int),FieldAttributes.Public);return 0;}catch(InvalidOperationException){return 42;} }
 public static int DuplicateNameIdentity() { var one=Type("SameType").CreateType()!;var two=Type("SameType").CreateType()!;return one!=two&&one.FullName==two.FullName?42:0; }
 public static int Indexer() {var t=Type("IndexerType");var p=t.DefineProperty("Item",PropertyAttributes.None,typeof(int),new[]{typeof(int)});var m=t.DefineMethod("get_Item",MethodAttributes.Public|MethodAttributes.SpecialName,typeof(int),new[]{typeof(int)});var il=m.GetILGenerator();il.Emit(OpCodes.Ldarg_1);il.Emit(OpCodes.Ldc_I4_2);il.Emit(OpCodes.Mul);il.Emit(OpCodes.Ret);p.SetGetMethod(m);var ct=t.CreateType()!;return (int)ct.GetProperty("Item")!.GetValue(Activator.CreateInstance(ct),new object[]{21})!;}
}
