using System;using System.Text;using System.Text.Json;using System.Collections.Generic;
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var result=new Dictionary<int,object>();
foreach(int cp in new[]{437,850,852,855,857,858,860,861,862,863,864,865,866,869,874,1250,1251,1252,1253,1254,1255,1256,1257,1258,28591}){
 var e=Encoding.GetEncoding(cp);var decode=new int[256];for(int b=0;b<256;b++)decode[b]=e.GetString(new[]{(byte)b})[0];
 var encode=new List<int>();for(int c=0;c<65536;c++){if(c>=0xd800&&c<=0xdfff)continue;var b=e.GetBytes(new string((char)c,1));if(b.Length==1&&b[0]!=63){encode.Add(c);encode.Add(b[0]);}}
 var aliases=new List<string>();foreach(var alias in new[]{e.WebName,"cp"+cp,"windows-"+cp,"ibm"+cp}){try{if(Encoding.GetEncoding(alias).CodePage==cp&&!aliases.Contains(alias))aliases.Add(alias);}catch(ArgumentException){}}
 result[cp]=new{webName=e.WebName,windowsCodePage=e.WindowsCodePage,aliases,decode,encode};
}
Console.WriteLine("/** Generated by tests/io-codepages-generator against .NET 10; byte decoding and BMP best-fit encoding for the listed single-byte pages. */");
Console.WriteLine("export const codePageData = "+JsonSerializer.Serialize(result)+";");
