using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
if(args.Length<3)throw new ArgumentException("Expected project root, pinned core reference directory, extracted desktop reference directory");
var root=Path.GetFullPath(args[0]);var core=args[1];var desktop=args[2];
var output=new Dictionary<string,object>();
foreach(var kind in new[]{"Forms","Wpf"}){
 var extra=kind=="Forms"?new[]{"System.Windows.Forms","System.Windows.Forms.Primitives","System.Drawing.Common"}:new[]{"WindowsBase","PresentationCore","PresentationFramework","System.Xaml"};
 var refs=Directory.GetFiles(core,"*.dll").Where(f=>!extra.Contains(Path.GetFileNameWithoutExtension(f))).OrderBy(f=>Path.GetFileName(f),StringComparer.Ordinal).Select(f=>MetadataReference.CreateFromFile(f)).ToList();
 var referenceMetadata=new List<object>();
 foreach(var name in extra){var path=Path.Combine(desktop,name+".dll");refs.Add(MetadataReference.CreateFromFile(path));referenceMetadata.Add(new{name,identity=AssemblyName.GetAssemblyName(path).FullName,sha256=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))).ToLowerInvariant()});}
 var source=File.ReadAllText(Path.Combine(root,"tests/desktop/Official"+kind+".cs"));
 var compilation=CSharpCompilation.Create("Original"+kind,new[]{CSharpSyntaxTree.ParseText(source,path:"Official"+kind+".cs")},refs,new CSharpCompilationOptions(OutputKind.ConsoleApplication,deterministic:true));
 using var stream=new MemoryStream();var result=compilation.Emit(stream);
 foreach(var d in result.Diagnostics.Where(d=>d.Severity==DiagnosticSeverity.Error))Console.Error.WriteLine(d);
 if(!result.Success)return 1;
 var bytes=stream.ToArray();using var pe=new PEReader(new MemoryStream(bytes));var md=pe.GetMetadataReader();
 var requested=md.AssemblyReferences.Select(h=>{var reference=md.GetAssemblyReference(h);return new{name=md.GetString(reference.Name),version=reference.Version.ToString(),publicKeyToken=Convert.ToHexString(md.GetBlobBytes(reference.PublicKeyOrToken)).ToLowerInvariant()};}).ToArray();
 output[kind.ToLowerInvariant()]=new{source,sha256=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(),peBase64=Convert.ToBase64String(bytes),requestedAssemblies=requested,officialReferences=referenceMetadata};
 Console.WriteLine($"Compiled Original{kind}.dll ({bytes.Length} bytes) against official reference assemblies");
}
var json=JsonSerializer.Serialize(new{provenance=new{package="Microsoft.WindowsDesktop.App.Ref",version="10.0.0",compiler=typeof(CSharpCompilation).Assembly.GetName().Version!.ToString()},forms=output["forms"],wpf=output["wpf"]},new JsonSerializerOptions{WriteIndented=true})+"\n";
var targets=new Dictionary<string,string>{{"demo/desktop-binaries.json",json},{"demo/desktop-binaries.js","// Generated by scripts/prepare-desktop-fixtures.sh from original official desktop references.\nexport default "+json.TrimEnd()+";\n"}};
foreach(var target in targets){var path=Path.Combine(root,target.Key);if(args.Contains("--check")){if(File.ReadAllText(path)!=target.Value){Console.Error.WriteLine("Committed desktop fixtures differ from deterministic original-reference compilation: "+target.Key);return 1;}}else File.WriteAllText(path,target.Value);}
if(args.Contains("--check"))Console.WriteLine("Committed binary fixtures reproduce exactly");
return 0;
